### ISSUE TITLE
Not working wwith kivy 1.10

### ISSUE THREAD

**Issue by thica** [kivy-garden/garden.scrolllabel#4]
if you use kivy 1.10 (and change the import of recycleview to kivy.uix.recycleview) you get no output from the wigget.

**Comment by frankyrumple** [comment]
Try editing the definition of the KV scroll label to add the RecycleBoxLayout and set the viewclass to label.

```
Builder.load_string("""
<ScrollLabel>:
    RecycleView:
        id: rv
        pos: root.pos
        size: root.size
        #key_viewclass: "viewclass"
        #key_size: "height"
        viewclass: 'Label'
        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'
    

<-ScrollLabelPart>:
    canvas:
        Color:
            rgba: (1, 1, 1, 1)
        Rectangle:
            pos: self._rect_x, self.y
            size: self.texture_size
            texture: root.texture
""")
```
